AllCops:
  NewCops: enable
  Exclude:
    - 'app/graphql/garden_grow_be_schema.rb'

Lint/UselessAssignment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false